name: fetch and update blog entries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch and Modify blog entries
        run: |
          ./update_blog_entries.sed
          git status

      - name: Commit and push if there are changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto update"
            git push
          else
            echo "No changes to commit"
          fi
